### ISSUE TITLE
Add tests and relevant integrations 

### ISSUE THREAD

**Issue by DhairyaLGandhi** [FluxML/Torch.jl#12]

**Comment by dhairyagandhi96** [comment]
Seems like we are at the point where we can move around the system with CNNs and backdrop. Next target is to have the rest of the tests in.

**Comment by bjosv79** [comment]
Hi,
I do not know your thoughts about test strategy. If it helps, single layer NNlib tests are available at https://github.com/bjosv79/Torch.jl/tree/test-nnlib.

The increased test coverage revealed a few issues.

**Comment by DhairyaLGandhi** [comment]
Brilliant! We should add these tests to the regular package !
