### ISSUE TITLE
Clarify if Python is needed in the README

### ISSUE THREAD

**Issue by juliohm** [FluxML/Torch.jl#39]
Can you please clarify if Python is needed? Do you interface with Torch directly or Python must be installed?

**Comment by DhairyaLGandhi** [comment]
There is no python dependency with this package. We use the cpp binaries and expose the same kernels as torch, without needing python in the mix.

**Comment by juliohm** [comment]
Perhaps making it explicit in the README would be a good idea. You mention PyTorch there and so people may think Python is playing a role somewhere.

**Comment by DhairyaLGandhi** [comment]
A PR with the preferred wording would be appreciated!

**Comment by DhairyaLGandhi** [comment]
Closed on master
