### ISSUE TITLE
Failed installing Torch.jl

### ISSUE THREAD

**Issue by JinraeKim** [FluxML/Torch.jl#50]
Simply `add Torch` results in this error:
```julia
ERROR: LoadError: InitError: could not load library "/home/jinrae/.julia/artifacts/d6ce2ca09ab00964151aaeae71179deb8f9800d1/lib/libdoeye_caml.so"
libcufft.so.10: cannot open shared object file: No such file or directory
```

with `nvidia-smi` output said:
Driver Version: 460.106.00
CUDA Version: 11.2
GPU: GeForce RTX 2070

**Comment by overshiki** [comment]
+1
I also encountered this problem, is there anyone who has a clue of what's going on?

**Comment by DhairyaLGandhi** [comment]
Can you try adding master? We can cut a release to reinstate the
functionality.

**Comment by overshiki** [comment]
Hi @DhairyaLGandhi 
Do you mean this:
```
add https://github.com/FluxML/Torch.jl.git
```

I tried this, but unfortunately, it does not work either. It raises the same error as `add Torch`. Namely, the `libdoeye_caml.so` file is missing.

To be more specific, the error I faced is slightly different from that of @JinraeKim :
```
ERROR: LoadError: InitError: could not load library "/home/le/.julia/artifacts/d6ce2ca09ab00964151aaeae71179deb8f9800d1/lib/libdoeye_caml.so"
libcuda.so.1: cannot open shared object file: No such file or directory
```

And I'm on a platform without a GPU(I just want to check the CPU version)

Thanks a lot if this problem could be solved, I'm doing some experiments to use PyTorch models in a Julia environment, and currently I'm highly replying on `PyCall` .

**Comment by ToucheSir** [comment]
I don't think things will work until all the points in https://github.com/FluxML/Torch.jl/issues/54#issuecomment-1264575111 are complete, unfortunately. In the meantime, check out https://github.com/rejuvyesh/PyCallChainRules.jl and possibly https://github.com/lorenzoh/PyNNTraining.jl if you want better integration with PyTorch models.
